# Generated by Django 3.0 on 2020-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='present', max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
