# Generated by Django 3.0 on 2020-01-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_attendance_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_submit',
            name='username',
        ),
    ]
